from publicweb.tests.decisions_test import DecisionsTest
from publicweb.tests.login_test import LoginTest
from publicweb.tests.logout_test import LogoutTest
from publicweb.tests.internationalisation_test import InternationalisationTest
#from publicweb.tests.open_consent_test_case import OpenConsentTestCase