from publicweb.tests.decisions_test import DecisionsTest
from publicweb.tests.login_test import LoginTest
from publicweb.tests.internationalisation_test import InternationalisationTest
from publicweb.tests.add_decision_test import AddDecisionTest
from publicweb.tests.decision_list_test import DecisionListTest
from publicweb.tests.decision_table_test import DecisionTableTest
from publicweb.tests.feedback_test import FeedbackTest
from publicweb.tests.email_test import EmailTest
from publicweb.tests.csv_test import CsvTest
