from decisions_test import DecisionsTest
from edit_decision_test import EditDecisionTest
from view_decision_test import ViewDecisionTest
from login_test import LoginTest
from logout_test import LogoutTest
from internationalisation_test import InternationalisationTest
from add_decision_test import AddDecisionTest
from decision_list_test import DecisionListTest
from feedback_test import FeedbackTest
from email_test import EmailTest
from csv_test import CsvTest
from tag_test import TagsTest
from model_test import ModelTest
from view_test import ViewTest
from url_test import URLTest
from form_test import FormTest
from html_test import HtmlTest
from command_test import CommandTest
